# External variables Settable at queue time:
# "pomFile" : "pom.xml".   This is the project object model file for Maven.

trigger:
  - master

variables:
  DefaultOptions: '--batch-mode -Dmaven.wagon.http.pool=false'
  LoggingOptions: '-Dorg.slf4j.simpleLogger.defaultLogLevel=error -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'

jobs:
  - job: 'Build'

    pool:
      vmImage: 'ubuntu-16.04'

    strategy:
      matrix:
        Java 8:
          ArtifactName: 'packages'
          ProfileFlag: ''
          JavaVersion: '1.8'
        Java 7:
          ArtifactName: 'packages'
          ProfileFlag: ''
          JavaVersion: '1.7'
          
    
    steps:      
      - task: Maven@3
        displayName: 'install'
        inputs:
          mavenPomFile: pom.xml
          options: '$(DefaultOptions) $(ProfileFlag) -pl !azure-samples javadoc:aggregate -DskipTests=true -DpackageOutputDirectory=$(Build.ArtifactStagingDirectory)" -am'
          mavenOptions: '$(LoggingOptions)'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(JavaVersion)
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          goals: 'install'
          
      - task: Maven@3
        displayName: 'Run StyleCheck'
        inputs:
          mavenPomFile: pom.xml
          options: '$(DefaultOptions) $(ProfileFlag)'
          mavenOptions: '$(LoggingOptions)'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(JavaVersion)
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          goals: 'checkstyle:check'
          
      - task: ShellScript@2 
        displayName: 'Set Ulimits' 
        inputs: 
          scriptPath: ci/setUlimits.sh 

      - task: Maven@3
        displayName: 'Start Jetty'
        inputs:
          mavenPomFile: pom.xml
          options: '$(ProfileFlag)'
          mavenOptions: '$(LoggingOptions)'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(JavaVersion)
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          goals: 'jetty:run-forked'
          
      - task: Maven@3
        displayName: 'Run Tests'
        inputs:
          mavenPomFile: pom.xml
          options: '$(DefaultOptions) $(ProfileFlag) -Dsurefire.rerunFailingTestsCount=3 -Dparallel=classes -DthreadCount=2 -DforkCount=1C'
          mavenOptions: '$(LoggingOptions)'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(JavaVersion)
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          goals: 'test'
          

      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          mergeTestResults: true
          testRunTitle: 'On Java $(JavaVersion)'
          

        