# External variables Settable at queue time:
# "pomFile" : "pom.xml".   This is the project object model file for Maven.

trigger:
  - master

variables:
  LoggingOptions: '-Dorg.slf4j.simpleLogger.defaultLogLevel=error -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'
  pomFile: 'pom.xml'

jobs:
  - job: 'Build'

    pool:
      vmImage: 'ubuntu-16.04'

    strategy:
      matrix:
        Java 8:
          ArtifactName: 'packages'
          ProfileFlag: ''
          JavaVersion: '1.8'
        Java 7:
          ArtifactName: 'packages'
          ProfileFlag: ''
          JavaVersion: '1.7'
          
    
    steps:
      - task: Maven@3
        displayName: 'Run jetty'
        inputs:
          mavenPomFile: $(pomFile)
          goals: 'jetty:run'
          mavenOptions: '$(LoggingOptions)'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: $(JavaVersion)
          jdkArchitectureOption: 'x64'
          
      - script: sleep 15
        displayName: 'Wait for jetty to start up'
      
      - task: ShellScript@2
        displayName: 'Run tests'
        inputs:
          scriptPath: ci/run_tests.sh
        